### ISSUE TITLE
Configurable keyboard hooks

### ISSUE THREAD

**Issue by gaearon** [gaearon/redux-devtools-dock-monitor#1]
We currently let user specify `toggleVisibilityKey` and `changePositionKey`, but this probably isn't enough because in some cases either `ctrl` messes things up, or `keypress` doesn't even get fired. We should probably expose a way to fully customize keyboard shortcuts, but it isn't obvious to me what kind of API is needed.

**Comment by quicksnap** [comment]
Not sure how related this is, but would you accept a PR for `Ctrl` + `Shift` + `Change Position Key` to switch positions in reverse order?

**Comment by gaearon** [comment]
Unrelated but yes :-)

**Comment by jlongster** [comment]
I came here to file this exact issue. Our app is already loaded with keyboard shortcuts so I need to find something really obscure, like ctrl+alt+shift+H or something. One option is to specify the key modifiers in the string itself, so the user could pass things like `ctrl+H` or `ctrl+cmd+H`. I bet there's an npm module out there for parsing strings like that.

**Comment by jlongster** [comment]
what about https://www.npmjs.com/package/parse-key ?

**Comment by gaearon** [comment]
Yes, we can use that, or even a library like https://craig.is/killing/mice

**Comment by jlongster** [comment]
That lib is quite a bit larger, but definitely seems more active. I guess it doesn't really matter though for devtools.

**Comment by gaearon** [comment]
I'm fine with either one, I just don't want to write a ton of code to correctly compare a browser event with a key representation, so I'd rather use something that does it already.

**Comment by gaearon** [comment]
Done via #4.
