### ISSUE TITLE
Any plans to release 1.0.0-beta-4?

### ISSUE THREAD

**Issue by DenisPostu** [gaearon/redux-devtools-dock-monitor#12]
Hey @gaearon,

Any plans to publish beta-4 to npm?
It contains some fixes that I am interested in, namely the fix for global event in DockMonitor that prevents it from working nicely in some browsers.

**Comment by gaearon** [comment]
I've been focused on another project (Egghead videos about Redux) for the past few weeks.
I expect next to finish them next week.
I will take care of releasing this package right after.
Sorry for delays.

**Comment by aeneasr** [comment]
Cool! :+1: on this because the keyboard bug is really annoying :D

Keep up the good work!

**Comment by JohanNordlinder** [comment]
+1 on this, I would really like 1e6980a to be included in a release. Thanks in advance!

**Comment by gaearon** [comment]
+1'ing issues doesn't help, sorry.
I'm busy and it won't make me less busy. 

You can help by making a PR again `next` branch in DevTools repo to write the README for the 3.0 version. Then we can release 3.0 with all the changes.

**Comment by SimenB** [comment]
`npm i gaearon/redux-devtools-dock-monitor` should work fine if you can't wait for a release. If you need it to be on the npm registry you can just publish a fork.

**Comment by johanhelsing** [comment]
@SimenB That won't work, since the package needs to be built. I created a temporary repo for this to work in my own project where I checked in the built lib folder.

Feel free to use my fork, but beware that I will delete it once a new upstream version is released.

https://github.com/johanhelsing/redux-devtools-dock-monitor

**Comment by gaearon** [comment]
Out as 1.0.1.
