### ISSUE TITLE
Plans to allow to toggle without modifiers ?

### ISSUE THREAD

**Issue by MoOx** [gaearon/redux-devtools-dock-monitor#16]
Currently we need to use ctrl + something.
I am currently working on a phonegap app, so sometimes I test on an actual smartphone and I would like to be able to hide redux devtools.
I am not sure how I can handle ctrl on an iphone :D
Any idea how we can handle that ?

**Comment by gaearon** [comment]
You can specify arbitrary shortcut with 1.0.1. (It requires DevTools 3.0)
