### ISSUE TITLE
child.type.update is not a function

### ISSUE THREAD

**Issue by terrysahaidak** [gaearon/redux-devtools-dock-monitor#21]
Please, push the new version to npm, because in npm it has this code:

``` js
// reducers.js
function childMonitorState(props, state, action) {
  var child = props.children;
  return child.type.update(child.props, state, action); 
}
```

but master branch is:

``` js
// reducers.js
function childMonitorState(props, state, action) {
  var child = props.children;
  return child.type.reducer(child.props, state, action); 
}
```

and it's don't wanna work :worried:

**Comment by gaearon** [comment]
It's actually the other way around—I forgot to push the local commits.
`child.type.update` is the final API.

**Comment by terrysahaidak** [comment]
It still does not work if the latest release is 1.0.1.
Just installed it and got the same error.
Simply change `update` to `reducer` and it's working.

**Comment by gaearon** [comment]
What monitor do you have _inside_ of `DockMonitor`?
Whatever it is, it's not compatible with DevTools 3.0.

Maybe you're using `redux-devtools-log-monitor@1.0.0-beta-3` instead of `1.0.1`?
Or some other monitor that hasn't been updated for DevTools 3.0 final.

**Comment by gaearon** [comment]
You can see that this version of package is used both in Redux DevTools examples and in Real World example in Redux repo. So it's not correct to say "it does not work". It does not work in some specific circumstances, but without clarifying them I can't help you.

**Comment by terrysahaidak** [comment]
I'm sorry, yes, I did use log-monitor beta-3 insead.
Thank you :)
