### ISSUE TITLE
Cannot read property 'position' of undefined

### ISSUE THREAD

**Issue by kevinold** [gaearon/redux-devtools-dock-monitor#24]
All of a sudden I'm seeing this error in my JS Console.  I'm starting to investigate, but wanted to log here.

<img width="1277" alt="screen shot 2015-12-29 at 11 44 57 am" src="https://cloud.githubusercontent.com/assets/21967/12038936/aa402dae-ae21-11e5-8829-501c3d33bb91.png">

**Comment by gaearon** [comment]
Please see:

https://github.com/gaearon/redux-devtools-dock-monitor/issues/22
https://github.com/gaearon/redux-devtools-dock-monitor/issues/6

You likely forgot `DevTools.instrument()` when creating a store.
There should also be a new warning about this if you use DevTools 3.0.1.
