### ISSUE TITLE
remember size

### ISSUE THREAD

**Issue by benmonro** [gaearon/redux-devtools-dock-monitor#25]
if I resize the dock monitor, then navigate to a new route, the dock monitor resizes back to it's original size.  It'd be nice if the monitor would remember the it's previous size/position/etc

**Comment by gaearon** [comment]
That's weird. Can you provide instructions and a project to reproduce this? Is this reproducible with Redux `real-world` example?

**Comment by benmonro** [comment]
it's an isomorphic app.  let me see if I can put together an example...

**Comment by gaearon** [comment]
When you say "navigate to a new route" do you mean `pushState` or a real navigation with new HTML?

**Comment by benmonro** [comment]
ok well, looks like creating the example highlighted that my client side routing is not working properly... however, I _still_ would like for the DockMonitor to remember my state, if i reload the browser, you'll see that the dock monitor goes back to it's initial size.  

Here's the example I created... might as well use it.  `npm start` will fire it up
https://github.com/benmonro/redux-dock-monitor-example

**Comment by benmonro** [comment]
@gaearon any thoughts on persisting the Dock monitor state?  It would be nice for it to remember the size of the dock even after I refresh the browser

**Comment by benmonro** [comment]
@gaearon another thing I'd like to see...  If I set the dock to be hidden by default, but give it a hot key to show/hide, it'd be nice if it remembered whether or not it was hidden if I reload the page as well...

**Comment by gaearon** [comment]
This is exactly what happens if you use `persistState()` enhancer from the main DevTools repo.

**Comment by benmonro** [comment]
ah ok, I had some outdated code for that, updated it and it's working now, thanks!
