### ISSUE TITLE
Support for multiple monitors?

### ISSUE THREAD

**Issue by chrishowes** [gaearon/redux-devtools-dock-monitor#27]
Might be out of scope for the project (if so, let me know and I'll try to help out), but I'd love to see the DockMonitor be able to take multiple children - possibly displaying them as tabs, etc.

**Comment by LabiKyo** [comment]
:+1:

**Comment by gaearon** [comment]
I’m up for adding this. I think a `<select>`-like interface would be the best. Would you like to give it a try?

**Comment by gaearon** [comment]
This was added in 1.1.0.
