### ISSUE TITLE
defaultIsVisible & defaultPosition don't seem to do anything

### ISSUE THREAD

**Issue by shotor** [gaearon/redux-devtools-dock-monitor#28]
Trying to start the dock monitor hidden:

```
const DevTools = createDevTools(
  <DockMonitor
    toggleVisibilityKey="ctrl-h"
    changePositionKey="ctrl-q"
    defaultPosition="left"
    defaultIsVisible={false}
  >
      <ChartMonitor />
  </DockMonitor>
);
```

But it doesn't seem to be doing anything. Looking through the source of DockMonitor, I don't see these two props being used anywhere.

As a test added in DockMonitor compiled code:

```
  DockMonitor.prototype.componentWillMount = function componentWillMount() {
    var _props = this.props;
    var monitorState = _props.monitorState;
    monitorState.isVisible = _props.defaultIsVisible;
  }
```

Seems to solve my problem. Am I overlooking something?

**Comment by ericlau-solid** [comment]
My mistake ... setting defaultIsVisible = {false} works.

**Comment by gaearon** [comment]
It should work. If it doesn’t please share the project reproducing the issue. Please note that `defaultIsVisible` only has any effect when you don’t use `persistState()` enhancer, as the persisted value will be preferred over the prop.
