### ISSUE TITLE
"event is not defined" with 1.0.0-beta-3

### ISSUE THREAD

**Issue by insin** [gaearon/redux-devtools-dock-monitor#3]
The version published to npm doesn't contain this change: ecc67af0e3f973d0bd915453253e6b1f88c1407c

**Comment by gaearon** [comment]
Yes. It also doesn't contain #2 or #4 :-)
I'm waiting for a few changes to accumulate before releasing the new beta, please give it a few more days!

**Comment by gaearon** [comment]
Fixed in 1.0.1. Requires DevTools 3.0 stable.
