### ISSUE TITLE
Dock Monitor is white and has artifacts on dropdown menus

### ISSUE THREAD

**Issue by EliasJorgensen** [gaearon/redux-devtools-dock-monitor#37]
My dock is looking discolored, and the arrows on the state dropdown menus are having "artifacts".
I'd supply you with some information to make it easier for you to help out, but quite frankly, i don't know what you'd need. I followed the Redux Devtools Walkthrough, in setting it up.

This is how it looks:
![image](https://cloud.githubusercontent.com/assets/3519438/16652469/27b56b86-444b-11e6-921b-2f7794a61330.png)

**Comment by alexkuz** [comment]
Could it be that some styles of your page override monitor styles?

If it's not the case - what does this command return? (I wonder which versions you are using exactly)

``` bash
npm list | grep -E "(redux-devtools|react-json-tree)"
```

**Comment by alexkuz** [comment]
For example, I reproduced it by defining global `div` style:

``` css
div {
  background: #FFF;
}
```

**Comment by EliasJorgensen** [comment]
You were right, there was a global div state, which my collaborator had set, apparently.
Thanks for the help, it would've taken me a while to debug on my own! Have a nice day!
