### ISSUE TITLE
Default values for required props

### ISSUE THREAD

**Issue by hendore** [gaearon/redux-devtools-dock-monitor#40]
Is there any particular reason why both toggleVisibilityKey and changePositionKey props can't have default values set?

**Comment by jvt** [comment]
To the best of my knowledge, there is no specific reason to not have default values set other than wanting to be agnostic to applications that this package might be used in. Applications may have their own shortcuts defined internally which our defaults may conflict with. Personally I see no reason to set sensible defaults and let those applications override them to something more fitting for their application.
