### ISSUE TITLE
Uncaught TypeError: Cannot read property 'position' of undefined

### ISSUE THREAD

**Issue by bolasblack** [gaearon/redux-devtools-dock-monitor#6]
I learn the usage from the example https://github.com/gaearon/redux-devtools/tree/next/examples/counter : 

``` coffeescript
DevTools = createDevTools(
  <DockMonitor toggleVisibilityKey='H' changePositionKey='Q'>
    <LogMonitor />
  </DockMonitor>
)

ReactDOM.render(
  <div>
    <Provider store={store}>
      <div>
        <App />
        <DevTools />
      </div>
    </Provider>
  </div>
  document.getElementById('app')
)
```

Then `DockMonitor` throw an Error `Uncaught TypeError: Cannot read property 'position' of undefined`, I found it caused by the code https://github.com/gaearon/redux-devtools-dock-monitor/blob/master/src/DockMonitor.js#L74, because `props.monitorState` is not exist.

Is any step I missed?

**Comment by gaearon** [comment]
Please write versions of all the packages you use.

**Comment by bolasblack** [comment]
Sorry for my mistake, all packages I'm using:

``` json
  "dependencies": {
    "bluebird": "2.9.34",
    "bootstrap": "twbs/bootstrap#v4.0.0-alpha",
    "moment": "2.10.6",
    "ramda": "0.17.1",
    "react": "0.14.0",
    "react-bootstrap": "0.27.1",
    "react-dom": "0.14.0",
    "react-redux": "4.0.0",
    "redux-thunk": "1.0.0",
    "xml2js": "0.4.10"
  },
  "devDependencies": {
    "coffee-jsx-loader": "0.1.3",
    "coffee-react": "4.0.0",
    "coffee-script": "1.10.0",
    "css-loader": "0.19.0",
    "gulp": "3.9.0",
    "gulp-sass": "2.0.4",
    "gulp-util": "3.0.6",
    "jest-cli": "0.5.8",
    "lodash": "3.10.1",
    "node-sass": "3.3.3",
    "react-addons-test-utils": "0.14.0",
    "redux-devtools": "3.0.0-beta-3",
    "redux-devtools-dock-monitor": "1.0.0-beta-3",
    "redux-devtools-log-monitor": "1.0.0-beta-3",
    "sass-loader": "3.0.0",
    "style-loader": "0.12.4",
    "webpack": "1.12.2",
    "webpack-dev-server": "1.11.0",
    "webpack-stream": "2.1.1"
  }
```

**Comment by bolasblack** [comment]
Sorry for my mistake, all packages I'm using:

```json
  "dependencies": {
    "bluebird": "2.9.34",
    "bootstrap": "twbs/bootstrap#v4.0.0-alpha",
    "moment": "2.10.6",
    "ramda": "0.17.1",
    "react": "0.14.0",
    "react-bootstrap": "0.27.1",
    "react-dom": "0.14.0",
    "react-redux": "4.0.0",
    "redux-thunk": "1.0.0",
    "xml2js": "0.4.10"
  },
  "devDependencies": {
    "coffee-jsx-loader": "0.1.3",
    "coffee-react": "4.0.0",
    "coffee-script": "1.10.0",
    "css-loader": "0.19.0",
    "gulp": "3.9.0",
    "gulp-sass": "2.0.4",
    "gulp-util": "3.0.6",
    "jest-cli": "0.5.8",
    "lodash": "3.10.1",
    "node-sass": "3.3.3",
    "react-addons-test-utils": "0.14.0",
    "redux-devtools": "3.0.0-beta-3",
    "redux-devtools-dock-monitor": "1.0.0-beta-3",
    "redux-devtools-log-monitor": "1.0.0-beta-3",
    "sass-loader": "3.0.0",
    "style-loader": "0.12.4",
    "webpack": "1.12.2",
    "webpack-dev-server": "1.11.0",
    "webpack-stream": "2.1.1"
  }
```

**Comment by gaearon** [comment]
Can you publish a minimal project reproding the issue? Also make sure to clear local storage once if you use persistState().

**Comment by newoga** [comment]
Hey @bolasblack, 

This may or may not be your issue, but I also just ran into this same error and it was because I forgot to add `DevTools.instrument()` to my store enhancing function.

See this [example](https://github.com/gaearon/redux-devtools/blob/next/examples/todomvc/store/configureStore.dev.js#L7)

**Comment by gaearon** [comment]
If this is the case, let's leave it open for now, because we should have a good warning for that..

**Comment by bolasblack** [comment]
Finally, I found I called `compose` twice with a mistake, and the second calling hasn't use `DevTools.instrument()`...

@gaearon I'm so sorry wasted your time, and so much thanks for your awesome work...

**Comment by gaearon** [comment]
Superseded by https://github.com/gaearon/redux-devtools/issues/179.

**Comment by torgeir** [comment]
I also hit this, calling `require('dev-tools').instrument()` directly, and not the `.instrument()` on my `createDevTools(..)`-created dev-tools.
